name: Deploying React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Building The App
        run: |
          npm install --production \
          npm run build
  deploy:
    runs-on: self-hosted
    steps:
      - name: Copying the files to ngx folder
        run: |
          sudo mv ~/_work/Portfolio-Website/dist/* /var/www/html
          sudo systemctl restart nginx
