name: Deploying React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Installing Dependencies
        run: npm install

      - name: Building The App
        run: |
          npm run build 
          pwd

      - name: Copying the files to ngx folder
        run: |
          sudo mv dist/* /var/www/portfolio/ && echo "Files moved successfully." || echo "Failed to move files."

      - name: Reload Nginx
        run: |
          sudo systemctl restart nginx
