name: Deploying React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Installing Dependencies
        run: npm install

      - name: Building the App
        run: npm run build

      - name: Moving the App to the serving directory
        run: sudo mv /home/ubuntu/portfolio/_work/Portfolio-Website/Portfolio-Website/dist/* /var/www/harkirat.site/

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
