name: Deploying React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Installing Dependencies
        run: npm install

      - name: Building The App
        run: npm run build

      - name: List Directory Contents
        run: ls -R
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Copying the files to ngx folder
        run: |
          sudo mv dist/* /var/www/html
          sudo systemctl restart nginx
