name: Deploying React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Installing Dependencies
        run: |
          npm install
      - name: Building the App
        run: |
          npm run build
          pwd
